# Generated by Django 5.0.8 on 2025-09-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
