# Generated by Django 5.0.8 on 2025-09-14 20:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="current_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=16
            ),
        ),
    ]
