# Generated by Django 5.0.8 on 2025-09-20 19:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_account_current_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="expected_return_annual_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="retirement_fund_type",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="broker",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[
                    ("ETF_STOCKS", "Acciones / ETF"),
                    ("RETIREMENT", "Retirement / Tax-Advantaged"),
                    ("BONDS", "Bonds"),
                    ("FUNDS", "Mutual Funds / Funds"),
                    ("CASH", "Cash"),
                ],
                default="ETF_STOCKS",
                max_length=16,
            ),
        ),
    ]
